// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cafkborqsvtpbjnydfki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZmtib3Jxc3Z0cGJqbnlkZmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzg2NTksImV4cCI6MjA2NTg1NDY1OX0.yIAh4tIwbsMOg0sJEkro7GXg9KBKpKcJMZAk3F-yPfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});